# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1HqNDz_afeO4vqBABTmc49B0pxzvB7TOA
"""

import numpy as np
import torch
print(torch.__version__)

import numpy as np
import matplotlib.pyplot as plt

# Physical constants
g = 9.81      # gravity (m/s^2)
L = 1.0       # pendulum length (m)

def pendulum_deriv(state, t):
    theta, omega = state
    dtheta_dt = omega
    domega_dt = -(g / L) * np.sin(theta)
    return np.array([dtheta_dt, domega_dt])

def simulate(theta0, omega0, t_max=10.0, dt=0.01):
    steps = int(t_max / dt)
    states = np.zeros((steps, 2))
    states[0] = [theta0, omega0]

    for i in range(1, steps):
        # Simple RK4 integration
        s = states[i-1]
        k1 = pendulum_deriv(s, 0)
        k2 = pendulum_deriv(s + dt/2 * k1, 0)
        k3 = pendulum_deriv(s + dt/2 * k2, 0)
        k4 = pendulum_deriv(s + dt * k3, 0)
        states[i] = s + (dt/6) * (k1 + 2*k2 + 2*k3 + k4)

    return states

# Simulate starting at 45 degrees, no initial velocity
theta0 = np.radians(45)
omega0 = 0.0
states = simulate(theta0, omega0)

# Plot angle over time
t = np.linspace(0, 10, len(states))
plt.figure(figsize=(10, 4))
plt.plot(t, np.degrees(states[:, 0]))
plt.xlabel("Time (s)")
plt.ylabel("Angle (degrees)")
plt.title("Pendulum motion (ground truth physics)")
plt.grid(True)
plt.savefig("pendulum_ground_truth.png")
plt.show()

def generate_dataset(n_trajectories=200, t_max=10.0, dt=0.01):
    X = []  # current state (theta, omega)
    Y = []  # next state (theta, omega)

    for _ in range(n_trajectories):
        theta0 = np.random.uniform(-np.pi/2, np.pi/2)  # random start angle
        omega0 = np.random.uniform(-1, 1)               # random start velocity
        states = simulate(theta0, omega0, t_max, dt)

        # pair each state with the very next state
        X.append(states[:-1])
        Y.append(states[1:])

    X = np.vstack(X)
    Y = np.vstack(Y)
    return X, Y

X, Y = generate_dataset()
print("Dataset shape:", X.shape, Y.shape)

import torch
import torch.nn as nn

# Convert data to PyTorch tensors
X_tensor = torch.tensor(X, dtype=torch.float32)
Y_tensor = torch.tensor(Y, dtype=torch.float32)

# Simple feedforward network: takes (theta, omega) -> predicts next (theta, omega)
class PendulumNet(nn.Module):
    def __init__(self, hidden_size=64):
        super().__init__()
        self.net = nn.Sequential(
            nn.Linear(2, hidden_size),
            nn.Tanh(),
            nn.Linear(hidden_size, hidden_size),
            nn.Tanh(),
            nn.Linear(hidden_size, 2)
        )

    def forward(self, x):
        return self.net(x)

model = PendulumNet()
print(model)

import torch.optim as optim

# Loss function and optimizer
criterion = nn.MSELoss()
optimizer = optim.Adam(model.parameters(), lr=0.001)

# Training loop
n_epochs = 50
batch_size = 256
n_samples = X_tensor.shape[0]

losses = []

for epoch in range(n_epochs):
    # Shuffle data each epoch
    perm = torch.randperm(n_samples)
    epoch_loss = 0.0

    for i in range(0, n_samples, batch_size):
        idx = perm[i:i+batch_size]
        x_batch = X_tensor[idx]
        y_batch = Y_tensor[idx]

        optimizer.zero_grad()
        pred = model(x_batch)
        loss = criterion(pred, y_batch)
        loss.backward()
        optimizer.step()

        epoch_loss += loss.item() * x_batch.shape[0]

    epoch_loss /= n_samples
    losses.append(epoch_loss)

    if epoch % 5 == 0 or epoch == n_epochs - 1:
        print(f"Epoch {epoch:3d} | Loss: {epoch_loss:.8f}")

def rollout_model(model, theta0, omega0, steps=999, dt=0.01):
    state = torch.tensor([theta0, omega0], dtype=torch.float32)
    trajectory = [state.numpy()]

    with torch.no_grad():
        for _ in range(steps):
            state = model(state.unsqueeze(0)).squeeze(0)
            trajectory.append(state.numpy())

    return np.array(trajectory)

# ============================================================================
# ENERGY DRIFT QUANTIFICATION
# ============================================================================

def compute_energy(trajectory, g=9.81, L=1.0):
    """
    Compute total mechanical energy (kinetic + potential) for a pendulum.
    
    Energy = (1/2) * m * L^2 * omega^2 + m * g * L * (1 - cos(theta))
    
    Since m and L are constant, we normalize by m*L^2:
    E_normalized = (1/2) * omega^2 + (g/L) * (1 - cos(theta))
    
    Args:
        trajectory: (N, 2) array where each row is [theta, omega]
        g: gravitational constant
        L: pendulum length
    
    Returns:
        energy: (N,) array of normalized total energy at each timestep
    """
    theta = trajectory[:, 0]
    omega = trajectory[:, 1]
    
    kinetic = 0.5 * omega**2
    potential = (g / L) * (1 - np.cos(theta))
    
    return kinetic + potential

def compute_energy_drift(true_energy, pred_energy):
    """
    Compute energy drift metrics.
    
    Args:
        true_energy: (N,) array of true energy values
        pred_energy: (N,) array of predicted energy values
    
    Returns:
        dict with drift metrics
    """
    # Initial energy
    E0_true = true_energy[0]
    
    # Absolute energy error
    energy_error = np.abs(pred_energy - true_energy)
    
    # Relative energy error
    relative_energy_error = energy_error / np.abs(E0_true)
    
    # Energy drift (change from initial)
    true_drift = np.abs(true_energy - E0_true)
    pred_drift = np.abs(pred_energy - E0_true)
    
    # Mean and max metrics
    metrics = {
        'initial_energy': E0_true,
        'mean_energy_error': np.mean(energy_error),
        'max_energy_error': np.max(energy_error),
        'mean_relative_error': np.mean(relative_energy_error),
        'max_relative_error': np.max(relative_energy_error),
        'true_energy_drift': true_drift,
        'pred_energy_drift': pred_drift,
        'true_energy': true_energy,
        'pred_energy': pred_energy,
    }
    
    return metrics

# Compare on a NEW starting condition (not seen in training)
theta0_test = np.radians(60)
omega0_test = 0.0

true_traj = simulate(theta0_test, omega0_test)
pred_traj = rollout_model(model, theta0_test, omega0_test)

# Compute energy for both trajectories
true_energy = compute_energy(true_traj)
pred_energy = compute_energy(pred_traj)

# Get energy drift metrics
drift_metrics = compute_energy_drift(true_energy, pred_energy)

print("\n" + "="*60)
print("ENERGY DRIFT ANALYSIS")
print("="*60)
print(f"Initial energy: {drift_metrics['initial_energy']:.6f}")
print(f"Mean energy error: {drift_metrics['mean_energy_error']:.8f}")
print(f"Max energy error: {drift_metrics['max_energy_error']:.8f}")
print(f"Mean relative error: {drift_metrics['mean_relative_error']:.6%}")
print(f"Max relative error: {drift_metrics['max_relative_error']:.6%}")
print("="*60 + "\n")

# Plot 1: Trajectory comparison (original)
t = np.linspace(0, 10, len(true_traj))

plt.figure(figsize=(12, 5))
plt.plot(t, np.degrees(true_traj[:, 0]), label="True physics (RK4)", linewidth=2)
plt.plot(t, np.degrees(pred_traj[:, 0]), label="Neural network rollout", linestyle="--")
plt.xlabel("Time (s)")
plt.ylabel("Angle (degrees)")
plt.title("True physics vs Neural network — full rollout")
plt.legend()
plt.grid(True)
plt.savefig("rollout_comparison.png")
plt.show()

# Plot 2: Energy over time
plt.figure(figsize=(12, 5))
plt.plot(t, drift_metrics['true_energy'], label="True energy", linewidth=2)
plt.plot(t, drift_metrics['pred_energy'], label="NN predicted energy", linestyle="--", linewidth=2)
plt.xlabel("Time (s)")
plt.ylabel("Total Energy (normalized)")
plt.title("Energy Conservation: True Physics vs Neural Network")
plt.legend()
plt.grid(True)
plt.savefig("energy_comparison.png")
plt.show()

# Plot 3: Energy error over time
plt.figure(figsize=(12, 5))
energy_error = np.abs(drift_metrics['pred_energy'] - drift_metrics['true_energy'])
plt.semilogy(t, energy_error, linewidth=2, color='red')
plt.xlabel("Time (s)")
plt.ylabel("Absolute Energy Error (log scale)")
plt.title("Energy Error Accumulation Over Time")
plt.grid(True, which='both', alpha=0.3)
plt.savefig("energy_error.png")
plt.show()

# Plot 4: Relative energy error over time
plt.figure(figsize=(12, 5))
relative_error = np.abs(drift_metrics['pred_energy'] - drift_metrics['true_energy']) / np.abs(drift_metrics['initial_energy'])
plt.semilogy(t, relative_error, linewidth=2, color='orange')
plt.xlabel("Time (s)")
plt.ylabel("Relative Energy Error (log scale)")
plt.title("Relative Energy Error Over Time")
plt.grid(True, which='both', alpha=0.3)
plt.savefig("relative_energy_error.png")
plt.show()
