# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1HqNDz_afeO4vqBABTmc49B0pxzvB7TOA
"""

import numpy as np
import torch
print(torch.__version__)

import numpy as np
import matplotlib.pyplot as plt

# Physical constants
g = 9.81      # gravity (m/s^2)
L = 1.0       # pendulum length (m)

def pendulum_deriv(state, t):
    theta, omega = state
    dtheta_dt = omega
    domega_dt = -(g / L) * np.sin(theta)
    return np.array([dtheta_dt, domega_dt])

def simulate(theta0, omega0, t_max=10.0, dt=0.01):
    steps = int(t_max / dt)
    states = np.zeros((steps, 2))
    states[0] = [theta0, omega0]

    for i in range(1, steps):
        # Simple RK4 integration
        s = states[i-1]
        k1 = pendulum_deriv(s, 0)
        k2 = pendulum_deriv(s + dt/2 * k1, 0)
        k3 = pendulum_deriv(s + dt/2 * k2, 0)
        k4 = pendulum_deriv(s + dt * k3, 0)
        states[i] = s + (dt/6) * (k1 + 2*k2 + 2*k3 + k4)

    return states

# Simulate starting at 45 degrees, no initial velocity
theta0 = np.radians(45)
omega0 = 0.0
states = simulate(theta0, omega0)

# Plot angle over time
t = np.linspace(0, 10, len(states))
plt.figure(figsize=(10, 4))
plt.plot(t, np.degrees(states[:, 0]))
plt.xlabel("Time (s)")
plt.ylabel("Angle (degrees)")
plt.title("Pendulum motion (ground truth physics)")
plt.grid(True)
plt.savefig("pendulum_ground_truth.png")
plt.show()

def generate_dataset(n_trajectories=200, t_max=10.0, dt=0.01):
    X = []  # current state (theta, omega)
    Y = []  # next state (theta, omega)

    for _ in range(n_trajectories):
        theta0 = np.random.uniform(-np.pi/2, np.pi/2)  # random start angle
        omega0 = np.random.uniform(-1, 1)               # random start velocity
        states = simulate(theta0, omega0, t_max, dt)

        # pair each state with the very next state
        X.append(states[:-1])
        Y.append(states[1:])

    X = np.vstack(X)
    Y = np.vstack(Y)
    return X, Y

X, Y = generate_dataset()
print("Dataset shape:", X.shape, Y.shape)

import torch
import torch.nn as nn

# Convert data to PyTorch tensors
X_tensor = torch.tensor(X, dtype=torch.float32)
Y_tensor = torch.tensor(Y, dtype=torch.float32)

# Simple feedforward network: takes (theta, omega) -> predicts next (theta, omega)
class PendulumNet(nn.Module):
    def __init__(self, hidden_size=64):
        super().__init__()
        self.net = nn.Sequential(
            nn.Linear(2, hidden_size),
            nn.Tanh(),
            nn.Linear(hidden_size, hidden_size),
            nn.Tanh(),
            nn.Linear(hidden_size, 2)
        )

    def forward(self, x):
        return self.net(x)

model = PendulumNet()
print(model)

import torch.optim as optim

# Loss function and optimizer
criterion = nn.MSELoss()
optimizer = optim.Adam(model.parameters(), lr=0.001)

# Training loop
n_epochs = 50
batch_size = 256
n_samples = X_tensor.shape[0]

losses = []

for epoch in range(n_epochs):
    # Shuffle data each epoch
    perm = torch.randperm(n_samples)
    epoch_loss = 0.0

    for i in range(0, n_samples, batch_size):
        idx = perm[i:i+batch_size]
        x_batch = X_tensor[idx]
        y_batch = Y_tensor[idx]

        optimizer.zero_grad()
        pred = model(x_batch)
        loss = criterion(pred, y_batch)
        loss.backward()
        optimizer.step()

        epoch_loss += loss.item() * x_batch.shape[0]

    epoch_loss /= n_samples
    losses.append(epoch_loss)

    if epoch % 5 == 0 or epoch == n_epochs - 1:
        print(f"Epoch {epoch:3d} | Loss: {epoch_loss:.8f}")

def rollout_model(model, theta0, omega0, steps=999, dt=0.01):
    state = torch.tensor([theta0, omega0], dtype=torch.float32)
    trajectory = [state.numpy()]

    with torch.no_grad():
        for _ in range(steps):
            state = model(state.unsqueeze(0)).squeeze(0)
            trajectory.append(state.numpy())

    return np.array(trajectory)

# Compare on a NEW starting condition (not seen in training)
theta0_test = np.radians(60)
omega0_test = 0.0

true_traj = simulate(theta0_test, omega0_test)
pred_traj = rollout_model(model, theta0_test, omega0_test)

t = np.linspace(0, 10, len(true_traj))

plt.figure(figsize=(12, 5))
plt.plot(t, np.degrees(true_traj[:, 0]), label="True physics (RK4)", linewidth=2)
plt.plot(t, np.degrees(pred_traj[:, 0]), label="Neural network rollout", linestyle="--")
plt.xlabel("Time (s)")
plt.ylabel("Angle (degrees)")
plt.title("True physics vs Neural network — full rollout")
plt.legend()
plt.grid(True)
plt.savefig("rollout_comparison.png")
plt.show()